server:
  port: 8084
eureka:
  instance:
    hostname: gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:

        - id: hotel-service
          uri: lb://hotel-service
          predicates:
              - Path=/api/v1/hotelservice/**
        - id: calification-service
          uri: lb://calification-service
          predicates:
              - Path=/api/v1/calificationservice/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
              - Path=/api/v1/authservice/**         
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
              - Path=/api/v1/**
